 
version: "3"
services:  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  server:
    container_name: server-container
    build: .
    image: mutant-api
    restart: always
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/usr/src/mutant/dist
    links:
      - elasticsearch    
volumes:
  data:
    driver: local
      

    